image: node:latest

stages:
    - build
    - test
    - deploy

build-job:    
    tags: 
        - windows   
    stage: build
    script:
        - npm build
    artifacts:
        paths:
            - build/

test-job:
    tags:
        - windows
    stage: test
    script:
        - ls
    
deploy-job:
    tags:
        - windows
    stage: deploy
    script:
        - echo "Deploying application..."
        - echo "Application successfully deployed."
