image: node:latest

stages:
    - build
    - test
    - deploy

build-job:    
    tags: 
        - docker  
    stage: build
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - build/

test-job:
    tags:
        - docker
    stage: test
    script:
        - ls
    
deploy-job:
    tags:
        - docker
    stage: deploy
    script:
        - echo "Deploying application..."
        - echo "Application successfully deployed."
